# Generated by Django 5.2 on 2025-05-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PERMISSION_APPROVED', 'Permiso Aprobado'), ('PERMISSION_REJECTED', 'Permiso Rechazado'), ('ACCESS_ENTRY', 'Registro de Entrada'), ('ACCESS_EXIT', 'Registro de Salida')], max_length=50, verbose_name='Tipo de Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del Objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
