# Generated by Django 5.2 on 2025-04-10 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@uab\\.edu\\.bo$', 'El correo debe ser del dominio @uab.edu.bo')], verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo se permiten letras y espacios')], verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo se permiten letras y espacios')], verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_usuario',
            field=models.CharField(choices=[('no asignado', 'No Asignado'), ('residente', 'Residente'), ('encargado', 'Encargado'), ('seguridad', 'Seguridad'), ('administrador', 'Administrador')], default='no asignado', max_length=20),
        ),
    ]
