# Generated by Django 5.2 on 2025-04-15 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuariopersonalizado_last_name_materno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='last_name_materno',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='last_name_paterno',
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo se permiten letras y espacios')], verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo se permiten letras y espacios')], verbose_name='apellido'),
        ),
    ]
