# Generated by Django 5.2 on 2025-04-15 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuariopersonalizado_last_name_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@uab\\.edu\\.bo$', 'El correo debe ser del dominio @uab.edu.bo.')], verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo se permiten letras y espacios.')], verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo se permiten letras y espacios.')], verbose_name='apellido paterno'),
        ),
    ]
