# Generated by Django 5.2 on 2025-05-19 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuariopersonalizado_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo se permiten letras y espacios.')], verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_usuario',
            field=models.CharField(choices=[('residente', 'Residente'), ('encargado', 'Encargado'), ('seguridad', 'Seguridad'), ('administrador', 'Administrador')], default='residente', max_length=20),
        ),
    ]
