# Generated by Django 5.2 on 2025-05-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('EXIT', 'Salida'), ('ENTRY', 'Entrada')], max_length=10, verbose_name='Tipo de Registro')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('permission', models.ForeignKey(limit_choices_to={'status': 'APPROVED'}, on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='a_permissions.permission')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
