# Generated by Django 5.2 on 2025-05-23 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_permissions', '0003_alter_permission_resident_alter_permission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('access_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida')], max_length=5, verbose_name='Tipo de Acceso')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_records', to='a_permissions.permission', verbose_name='Permiso Asociado')),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'RESIDENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to=settings.AUTH_USER_MODEL, verbose_name='Residente')),
                ('security_guard', models.ForeignKey(limit_choices_to={'role': 'SEGURIDAD'}, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Guardia de Seguridad')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
