# Generated by Django 5.2 on 2025-06-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado')], default='PENDING', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='access_type',
            field=models.CharField(choices=[('EXIT', 'Salida'), ('ENTRY', 'Entrada')], max_length=5, verbose_name='Tipo de Acceso'),
        ),
    ]
