# Generated by Django 5.2 on 2025-05-23 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='security_officer',
            field=models.ForeignKey(limit_choices_to={'role': 'SEGURIDAD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
