# Generated by Django 5.2 on 2025-05-23 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='approver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ENCARGADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='resident',
            field=models.ForeignKey(limit_choices_to={'role': 'RESIDENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='permissions_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
