# Generated by Django 5.2 on 2025-05-23 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_permissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resident',
            field=models.ForeignKey(limit_choices_to={'role': 'RESIDENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL, verbose_name='Residente'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('COMPLETED', 'Completado')], default='PENDING', max_length=20),
        ),
    ]
