# Generated by Django 5.2 on 2025-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_permissions', '0004_alter_permission_created_at_alter_permission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
